name: Black
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
      # git checkout
      - uses: actions/checkout@v3

      # python setup
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip

      # install black (extract version from versions.cfg)
      - name: install black
        run: pip install click==$(awk '/^click =/{print $NF}' versions.cfg) black==$(awk '/^black =/{print $NF}' versions.cfg)

      # run black
      - name: run black
        run: python -m black civo/